networks:
    laravel:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        build:
            context: ./src/fe_workshop
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"  # Hanya expose Nginx ke luar
        volumes:
            - ./src/workshop:/var/www/workshop
            - ./src/fe_workshop:/var/www/fe_workshop
            - ./src/pmw:/var/www/pmw
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - workshop
            - pmw
        networks:
            - laravel

    mysql_workshop:
        platform: linux/amd64
        image: mysql
        container_name: mysql_workshop
        restart: unless-stopped
        tty: true
        expose:
            - "3306"  # Tidak diekspos ke luar, hanya bisa diakses dalam jaringan Docker
        volumes:
            - ./mysql_workshop:/var/lib/mysql
        environment:
            MYSQL_DATABASE: pmw
            MYSQL_USER: wirausaha
            MYSQL_PASSWORD: Kewirausahaan2025
            MYSQL_ROOT_PASSWORD: Kewirausahaan2025
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    mysql_pekan_mahasiswa_wirausaha:
        platform: linux/amd64
        image: mysql
        container_name: mysql_pmw
        restart: unless-stopped
        tty: true
        expose:
            - "3306"  # Tidak diekspos ke luar
        volumes:
            - ./mysql_pmw:/var/lib/mysql
        environment:
            MYSQL_DATABASE: pmw
            MYSQL_USER: wirausaha
            MYSQL_PASSWORD: Kewirausahaan2025
            MYSQL_ROOT_PASSWORD: Kewirausahaan2025
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    workshop:
        build:
            context: .
            dockerfile: ./src/workshop/Dockerfile
        container_name: workshop
        working_dir: /var/www/workshop
        restart: unless-stopped
        volumes:
            - ./src/workshop:/var/www/workshop
        expose:
            - "9000"  # Tidak diekspos ke luar, hanya bisa diakses dalam jaringan Docker
        env_file:
            - ./src/workshop/.env
        tty: true
        depends_on:
            - mysql_workshop
        networks:
            - laravel

    pmw:
        build:
          context: .
          dockerfile: ./src/pmw/Dockerfile
        container_name: pmw
        working_dir: /var/www/pmw
        restart: unless-stopped
        expose:
            - "9000"  # Tidak diekspos ke luar
        volumes:
            - ./src/pmw:/var/www/pmw
        env_file:
            - ./src/pmw/.env
        depends_on:
            - mysql_pekan_mahasiswa_wirausaha
        tty: true
        networks:
            - laravel

