networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
            - "8000:8000"
        volumes: 
            - ./src/backend:/var/www/backend/app
            - ./src/frontend:/var/www/frontend/build/web
            - ./nginx/flutter_frontend.conf:/etc/nginx/conf.d/flutter_frontend.conf
            - ./nginx/laravel_backend.conf:/etc/nginx/conf.d/laravel_backend.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        platform: linux/amd64
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build:
            context: .
            dockerfile: ./src/backend/Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/backend/app
        volumes: 
            - ./src/backend:/var/www/backend/app
        ports:
            - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        networks:
            - laravel
