# nginx/frontend.conf
server {
    listen 8000;
    server_name _;

    # Konfigurasi untuk melayani aplikasi Flutter Web
    location / {
        root /var/www/frontend/app/build/web;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Mengatur error
    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
    }

    # Mengatur log error
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
