server {
    listen 80;
    server_name localhost;

    location = /workshop {
        return 301 /workshop/;
    }

    location /workshop/ {
        alias /var/www/workshop/public/;
        index index.php index.html;
        try_files $uri $uri/ @workshop;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass workshop:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            fastcgi_param PATH_INFO $fastcgi_path_info;
       }
    }

    location @workshop {
        rewrite ^/workshop/(.*)$ /workshop/index.php?$1 last;
    }

    location /pmw {
        return 301 /pmw/;
    }

    location /pmw/ {
        alias /var/www/pmw/public/;
        index index.php index.html;
        try_files $uri $uri/ @pmw;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass pmw:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }

    location @pmw {
        rewrite ^/pmw/(.*)$ /pmw/index.php?$1 last;
    }
    
    # Frontend Workshop
    location / {
        alias /var/www/fe_workshop/build/web/;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # error page to / 
    error_page 404 /;

    error_log /var/log/nginx/error.log debug;
    access_log /var/log/nginx/access.log;
}
