server {
    listen 80;
    server_name localhost;

    # 1. Jadikan /workshop-api sebagai backend yang sebelumnya ada di /workshop
    location = /workshop-api {
        return 301 /workshop-api/;
    }

    location /workshop-api/ {
        alias /var/www/workshop/public/;
        index index.php index.html;
        try_files $uri $uri/ @workshop_api;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass workshop:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }

    location @workshop_api {
        rewrite ^/workshop-api/(.*)$ /workshop-api/index.php?$1 last;
    }

    # 2. Jadikan /workshop sebagai frontend yang sebelumnya ada di /
    location /workshop/ {
        alias /var/www/fe_workshop/build/web/;
        index index.html;
        try_files $uri $uri/ =404;
    }

    location = /workshop {
        return 301 /workshop/;
    }

    # 3. Jadikan / sebagai backend PMW yang sebelumnya ada di /pmw
    location / {
        alias /var/www/pmw/public/;
        index index.php index.html;
        try_files $uri $uri/ @pmw;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass pmw:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }

    location @pmw {
        rewrite ^/(.*)$ /index.php?$1 last;
    }

    # error page to root
    error_page 404 /;
    error_log /var/log/nginx/error.log debug;
    access_log /var/log/nginx/access.log;
}

